//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorAppointment
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class appointmentInfo
    {
        public int appointment_Id { get; set; }
        public Nullable<int> doctor_Id { get; set; }
        public Nullable<int> patient_Id { get; set; }
        public string doctor_Name { get; set; }
        public string patient_Name { get; set; }
        public Nullable<System.DateTime> appointment_Date { get; set; }

        [Required]
        public Nullable<System.TimeSpan> appointment_Time { get; set; }
        public Nullable<bool> appointment_Status { get; set; }
        public string approvalStatus { get; set; }
    }
}
