//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorAppointment
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Appoinment_Entities : DbContext
    {
        public Appoinment_Entities()
            : base("name=Appoinment_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<userRole> userRoles { get; set; }
        public virtual DbSet<userLogin> userLogins { get; set; }
        public virtual DbSet<doctorDetail> doctorDetails { get; set; }
        public virtual DbSet<appointmentInfo> appointmentInfoes { get; set; }
        public virtual DbSet<user_Info> user_Info { get; set; }
    }
}
