//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorAppointment
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class doctorDetail
    {
        public int id { get; set; }
        public Nullable<int> doctor_Id { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
    
        public virtual userLogin userLogin { get; set; }
        public string Doctor_Name { get; set; }

        public List<SelectListItem> Interval { get; set; }
    }
}
